# Generated by Django 4.0.4 on 2022-05-26 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about', verbose_name='Hero image')),
                ('image_ru', models.ImageField(null=True, upload_to='about', verbose_name='Hero image')),
                ('image_en', models.ImageField(null=True, upload_to='about', verbose_name='Hero image')),
                ('text', models.TextField(max_length=500, verbose_name='Text body')),
                ('location', models.CharField(max_length=200, verbose_name='Blog location')),
                ('location_ru', models.CharField(max_length=200, null=True, verbose_name='Blog location')),
                ('location_en', models.CharField(max_length=200, null=True, verbose_name='Blog location')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Blog Tel')),
                ('phone_number_ru', models.CharField(max_length=100, null=True, verbose_name='Blog Tel')),
                ('phone_number_en', models.CharField(max_length=100, null=True, verbose_name='Blog Tel')),
                ('email_blog', models.EmailField(max_length=50, verbose_name='Blog email')),
                ('email_blog_ru', models.EmailField(max_length=50, null=True, verbose_name='Blog email')),
                ('email_blog_en', models.EmailField(max_length=50, null=True, verbose_name='Blog email')),
                ('contact_text', models.TextField(max_length=150, verbose_name='Additional description of contacts')),
            ],
            options={
                'verbose_name': ('About',),
                'verbose_name_plural': 'Abouts',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='card', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Svg image')),
                ('title', models.CharField(max_length=30, verbose_name='Card name')),
                ('title_ru', models.CharField(max_length=30, null=True, verbose_name='Card name')),
                ('title_en', models.CharField(max_length=30, null=True, verbose_name='Card name')),
                ('text', models.TextField(max_length=150, verbose_name='Card text')),
                ('text_ru', models.TextField(max_length=150, null=True, verbose_name='Card text')),
                ('text_en', models.TextField(max_length=150, null=True, verbose_name='Card text')),
            ],
            options={
                'verbose_name': ('Card',),
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name contact user')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Name contact user')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Name contact user')),
                ('email', models.EmailField(max_length=254, verbose_name='Email in form')),
                ('email_ru', models.EmailField(max_length=254, null=True, verbose_name='Email in form')),
                ('email_en', models.EmailField(max_length=254, null=True, verbose_name='Email in form')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject in form')),
                ('subject_ru', models.CharField(max_length=50, null=True, verbose_name='Subject in form')),
                ('subject_en', models.CharField(max_length=50, null=True, verbose_name='Subject in form')),
                ('message', models.TextField(max_length=500, verbose_name='Message from user')),
                ('message_ru', models.TextField(max_length=500, null=True, verbose_name='Message from user')),
                ('message_en', models.TextField(max_length=500, null=True, verbose_name='Message from user')),
            ],
            options={
                'verbose_name': ('Contact',),
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employee', verbose_name='Employee photo')),
                ('image_ru', models.ImageField(null=True, upload_to='employee', verbose_name='Employee photo')),
                ('image_en', models.ImageField(null=True, upload_to='employee', verbose_name='Employee photo')),
                ('name', models.CharField(max_length=30, verbose_name='Employee name')),
                ('name_ru', models.CharField(max_length=30, null=True, verbose_name='Employee name')),
                ('name_en', models.CharField(max_length=30, null=True, verbose_name='Employee name')),
                ('position', models.CharField(max_length=30, verbose_name='Position in the organization')),
                ('position_ru', models.CharField(max_length=30, null=True, verbose_name='Position in the organization')),
                ('position_en', models.CharField(max_length=30, null=True, verbose_name='Position in the organization')),
                ('text', models.TextField(max_length=200, verbose_name='Message from Employee')),
            ],
            options={
                'verbose_name': ('Team',),
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
